# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baretree < Formula
  desc "Centralized repository management with powerful Git worktree support"
  homepage "https://github.com/amaya382/baretree"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.3/baretree_0.2.3_darwin_x86_64.tar.gz"
      sha256 "2859655a4f8f72bc3cff1cc55ca2965e148679a9f31a4a74953d8974cc1d3d89"

      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.3/baretree_0.2.3_darwin_arm64.tar.gz"
      sha256 "b94bf82b7165ea9097b1d5db1ee34e3ae8c75e5e46d10541db2a2397bfe9c5ba"

      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.3/baretree_0.2.3_linux_x86_64.tar.gz"
      sha256 "1ef7225c6de29ea169fd891948e6d2249c143699510a3baf543467b5ff8c50d3"
      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.3/baretree_0.2.3_linux_arm64.tar.gz"
      sha256 "d817702647d68e3855627435ec8d55d1edafea7826dddb60e78d01760ee8abdf"
      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell completions and `cd` features, please restart your shell.
    EOS
  end
end
