# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baretree < Formula
  desc "Centralized repository management with powerful Git worktree support"
  homepage "https://github.com/amaya382/baretree"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amaya382/baretree/releases/download/v0.1.0/baretree_0.1.0_darwin_x86_64.tar.gz"
      sha256 "b1349dde6d9ee213ef925e7af4c75c4356d94ba2648f7280d63e532ca56a679b"

      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amaya382/baretree/releases/download/v0.1.0/baretree_0.1.0_darwin_arm64.tar.gz"
      sha256 "62fa72368a9773f5adefd352b5b9c067c3596a645d6e97744a82a2076359392b"

      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amaya382/baretree/releases/download/v0.1.0/baretree_0.1.0_linux_x86_64.tar.gz"
      sha256 "9a77ba7b6183b56a35df3799f047f3dc3aeb93dd36000fb1aeaf1ccec763f3a9"
      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amaya382/baretree/releases/download/v0.1.0/baretree_0.1.0_linux_arm64.tar.gz"
      sha256 "7ccb1f921008120ec5356110f92f86e93fd0f86e727dfb184b58952be0285a41"
      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell completions and `cd` features, please restart your shell.
    EOS
  end
end
