# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Baretree < Formula
  desc "Centralized repository management with powerful Git worktree support"
  homepage "https://github.com/amaya382/baretree"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.6/baretree_0.2.6_darwin_x86_64.tar.gz"
      sha256 "c9f011ba64d35f03a1a4c07f32df6fd5a21bb02eed997d4479928805d42ba648"

      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.6/baretree_0.2.6_darwin_arm64.tar.gz"
      sha256 "37e37ab3d722bba2e95a9a0817694b0facea2b53dcc2c01c9b1fef374d1d687d"

      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.6/baretree_0.2.6_linux_x86_64.tar.gz"
      sha256 "1d1c42d41cbe1733df9751239569eace50d1bf187fd904513d9a18a1b95f7cb2"
      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/amaya382/baretree/releases/download/v0.2.6/baretree_0.2.6_linux_arm64.tar.gz"
      sha256 "5458b57bb7a76cc77d0153ffea52b143e2aa81c5cfad81f0832f52c6b9d9612a"
      def install
        bin.install "bt"

        # Bash completion (Lazy load)
        (bash_completion/"bt").write <<~EOS
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init bash 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if declare -F _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          complete -o bashdefault -o default -o nospace -F _bt_lazy_init bt
        EOS

        # Zsh completion (Lazy load)
        (zsh_completion/"_bt").write <<~EOS
          #compdef bt
          _bt_lazy_init() {
            if [[ -z "${BT_SHELL_INIT_DONE:-}" ]]; then
              local __bt_init
              __bt_init="$(command bt shell-init zsh 2>/dev/null)"
              if [[ $? -eq 0 && -n "$__bt_init" ]]; then
                eval "$__bt_init"
                export BT_SHELL_INIT_DONE=1
              fi
            fi
            if typeset -f _bt_completion >/dev/null 2>&1; then
              _bt_completion "$@"
            fi
          }
          compdef _bt_lazy_init bt
        EOS

        (fish_completion/"bt.fish").write <<~'EOS'
          function __bt_lazy_setup --on-event fish_prompt --description 'Lazy shell-init for bt'
            functions -e __bt_lazy_setup

            if not set -q BT_SHELL_INIT_DONE
              command bt shell-init fish ^/dev/null | source
              set -l __bt_status $status
              if test $__bt_status -ne 0
                return
              end

              set -gx BT_SHELL_INIT_DONE 1
            end
          end
        EOS
      end
    end
  end

  def caveats
    <<~EOS
      To enable shell completions and `cd` features, please restart your shell.
    EOS
  end
end
